name = "vp_interop_app"

workers_dev = false
routes = ["app.vp.interop.spruceid.xyz/*", "app.vp.interop.spruceid.dev/*"]

compatibility_date = "2023-06-21"

[site]
bucket = "./dist"

[env.preview]
routes = []
workers_dev = true
