name = "vp_interop_app"
type = "webpack"
account_id = ""

workers_dev = false

zone_id = ""
routes = ["example.com/*"]

compatibility_date = "2022-11-03"

[vars]
API_BASE = "https://example.com"

# TODO always need to clean
[build]
command = "cargo install -q trunk && API_BASE='https://example.com' trunk build"

# TODO switch to wrangler v2

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
