[package]
name = "vp_interop_api"
version = "0.1.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "MIT OR Apache-2.0"
description = "JWT VC Presentation Profile"
repository = "https://github.com/spruceid/vp_interop/"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oidc4vp = { path = "../../oidc4vp-rs/" }
worker = "0.0.11"
wee_alloc = "0.4"
serde_json = "1"
headers = "0.3.8"
thiserror = "1.0.37"
anyhow = "1.0.66"
openidconnect = { version = "2.4.0", default-features = false }
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.0.1"
ssi = { path = "../../ssi" }
did-ion = { path = "../../ssi/did-ion" }
did-web = { path = "../../ssi/did-web" }

rand = "0.8.4"
# getrandom = { version = "0.2", features = ["js"] }
chrono = { version = "0.4.19", features = ["wasmbind"] }
uuid = { version = "1.2.1", features = ["serde", "v4", "wasm-bindgen", "js"] }
time = { version = "0.3.16", features = ["wasm-bindgen"] }
serde_urlencoded = "0.7.1"
lazy_static = "1.4.0"
async-trait = "0.1.58"

[dev-dependencies]
serde_path_to_error = "0.1.8"
pretty_assertions = "1.3.0"
tokio = { version = "1.21.2", features = ["macros"] }
