name = "vp_interop_api"
main = "build/worker/shim.mjs"
account_id = ""

workers_dev = false

routes = ["api.example.com/*"]

compatibility_date = "2022-11-21"

kv_namespaces = [
    { binding = "JWT_VC_INTEROP", id = "", preview_id = "" }
]

[vars]
WORKERS_RS_VERSION = "0.0.12"
BASE_URL = "https://api.example.com"
APP_BASE_URL = "https://example.com"
DID = "did:web:api.example.com"

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"
