name: cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-unknown"
      - name: Install trunk
        uses: baptiste0928/cargo-install@v2
        with:
          crate: trunk
      - name: Set env vars for production
        run: |
          echo "API_BASE=https://api.vp.interop.spruceid.xyz" >> $GITHUB_ENV
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Set env vars for preview
        run: |
          echo "API_BASE=https://vp_interop_api-preview.spruceid.workers.dev/" >> $GITHUB_ENV
          echo "ENVIRONMENT=--env preview" >> $GITHUB_ENV
        if: ${{ github.ref != 'refs/heads/main' }}
      - uses: Swatinem/rust-cache@v2
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build
        run: trunk build --release
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: npm install @cloudflare/kv-asset-handler@0.3.0
          command: deploy ${{ env.ENVIRONMENT }}
          workingDirectory: 'frontend'
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-unknown"
      - name: Install worker-build
        uses: baptiste0928/cargo-install@v2
        with:
          crate: worker-build
          version: "0.0.9"
      - uses: Swatinem/rust-cache@v2
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set env vars for preview
        run: |
          echo "ENVIRONMENT=--env preview" >> $GITHUB_ENV
        if: ${{ github.ref != 'refs/heads/main' }}
      - name: Build
        run: worker-build --release
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy ${{ env.ENVIRONMENT }}
          workingDirectory: 'api'
