name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings --cfg=web_sys_unstable_apis"

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Fmt
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: "wasm32-unknown-unknown"
    - uses: Swatinem/rust-cache@v2
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Build
      run: cargo build
    - name: Fmt
      run: cargo fmt -- --check
    # - name: Clippy
    #   run: cargo clippy
